version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=webflux-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - webflux_data:/var/lib/postgres
volumes:
  webflux_data: