
spring:
  r2dbc:
    url: ${WEBFLUX_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/webflux-db?schema=anime}
    username: ${WEBFLUX_DATASOURCE_USERNAME:postgres}
    password: ${WEBFLUX_DATASOURCE_PASSWORD:password}

logging:
  level:
    org.springframework.r2dbc: DEBUG
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
